### ISSUE TITLE
Facing circular dependency issue

### ISSUE THREAD

**Issue by dirkknibbe** [coinbase/cdp-agentkit#66]
So today I was just trying to follow the 5 minute quickstart guide here:

https://docs.cdp.coinbase.com/agentkit/docs/quickstart

tried running: poetry add twitter-langchain

and I get this error:

~/CDP-AgentKit-1$ poetry add twitter-langchain
Using version ^0.0.6 for twitter-langchain

Updating dependencies
Resolving dependencies... (0.0s)

Because no versions of twitter-langchain match >0.0.6,<0.0.7
 and twitter-langchain (0.0.6) depends on cdp-agentkit-core (>=0.0.6,<0.0.7), twitter-langchain (>=0.0.6,<0.0.7) requires cdp-agentkit-core (>=0.0.6,<0.0.7).
So, because cdp-agentkit-sample depends on both cdp-agentkit-core (^0.0.4) and twitter-langchain (^0.0.6), version solving failed.

tried changing the versions of all these packages, doesn't help any....

**Comment by John-peterson-coinbase** [comment]
Thanks for your question @dirkknibbe!

This [Replit template](https://replit.com/@lincolnmurr/X-Twitter-x-AgentKit#README.md) has all of the correct dependency versions to unblock you for Agentkit + X integration quickstart.

please let me know if you have any other questions.

**Comment by dirkknibbe** [comment]
oh sheesh ok I did not see that there was a whole other template needed...thank you
